using System;

namespace GaiaEngine.Domain.Genetics;

/// <summary>
/// Represents the deterministic phenotype generated by morphogenesis.
/// </summary>
public sealed record BodyPlan
{
    /// <summary>
    /// Initializes a new instance of the <see cref="BodyPlan"/> class.
    /// </summary>
    /// <param name="proportions">The normalized body proportion value scaled to [0, 1000].</param>
    /// <param name="mass">The normalized body mass value scaled to [0, 1000].</param>
    /// <param name="limbConfiguration">The normalized limb configuration value scaled to [0, 1000].</param>
    /// <param name="bodyCovering">The normalized body covering value scaled to [0, 1000].</param>
    /// <param name="coloration">The normalized coloration value scaled to [0, 1000].</param>
    /// <param name="sensoryStructures">The normalized sensory structure value scaled to [0, 1000].</param>
    /// <param name="locomotionProfile">The normalized locomotion profile value scaled to [0, 1000].</param>
    /// <param name="developmentModifier">The aggregate developmental modifier scaled to the inclusive range [-1000, 1000].</param>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when any normalized body value is outside the supported deterministic range.</exception>
    public BodyPlan(
        int proportions,
        int mass,
        int limbConfiguration,
        int bodyCovering,
        int coloration,
        int sensoryStructures,
        int locomotionProfile,
        int developmentModifier)
    {
        Proportions = ValidateNormalizedRange(proportions, nameof(proportions));
        Mass = ValidateNormalizedRange(mass, nameof(mass));
        LimbConfiguration = ValidateNormalizedRange(limbConfiguration, nameof(limbConfiguration));
        BodyCovering = ValidateNormalizedRange(bodyCovering, nameof(bodyCovering));
        Coloration = ValidateNormalizedRange(coloration, nameof(coloration));
        SensoryStructures = ValidateNormalizedRange(sensoryStructures, nameof(sensoryStructures));
        LocomotionProfile = ValidateNormalizedRange(locomotionProfile, nameof(locomotionProfile));

        if (developmentModifier < -1000 || developmentModifier > 1000)
        {
            throw new ArgumentOutOfRangeException(nameof(developmentModifier), "The development modifier must be between -1000 and 1000.");
        }

        DevelopmentModifier = developmentModifier;
    }

    /// <summary>
    /// Gets the normalized body proportion value scaled to [0, 1000].
    /// </summary>
    public int Proportions { get; }

    /// <summary>
    /// Gets the normalized body mass value scaled to [0, 1000].
    /// </summary>
    public int Mass { get; }

    /// <summary>
    /// Gets the normalized limb configuration value scaled to [0, 1000].
    /// </summary>
    public int LimbConfiguration { get; }

    /// <summary>
    /// Gets the normalized body covering value scaled to [0, 1000].
    /// </summary>
    public int BodyCovering { get; }

    /// <summary>
    /// Gets the normalized coloration value scaled to [0, 1000].
    /// </summary>
    public int Coloration { get; }

    /// <summary>
    /// Gets the normalized sensory structure value scaled to [0, 1000].
    /// </summary>
    public int SensoryStructures { get; }

    /// <summary>
    /// Gets the normalized locomotion profile value scaled to [0, 1000].
    /// </summary>
    public int LocomotionProfile { get; }

    /// <summary>
    /// Gets the aggregate developmental modifier scaled to the inclusive range [-1000, 1000].
    /// </summary>
    public int DevelopmentModifier { get; }

    private static int ValidateNormalizedRange(int value, string parameterName)
    {
        if (value < 0 || value > 1000)
        {
            throw new ArgumentOutOfRangeException(parameterName, "The body plan value must be between 0 and 1000.");
        }

        return value;
    }
}
