using System;

namespace GaiaEngine.Simulation.AI.Perception;

/// <summary>
/// Represents one deterministic observation generated by the perception system.
/// </summary>
public sealed record PerceivedObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PerceivedObject"/> class.
    /// </summary>
    /// <param name="objectId">The deterministic observed object identifier.</param>
    /// <param name="objectKind">The observed object category.</param>
    /// <param name="sensorType">The sensor that detected the object.</param>
    /// <param name="confidence">
    /// The deterministic confidence scaled to the inclusive range [0, 1000],
    /// which represents the specification range [0.0, 1.0].
    /// </param>
    /// <param name="distance">The non-negative chunk distance between observer and observed object.</param>
    /// <param name="detectionTick">The simulation tick when the detection occurred.</param>
    /// <exception cref="ArgumentOutOfRangeException">
    /// Thrown when <paramref name="confidence"/> is outside [0, 1000],
    /// when <paramref name="distance"/> is negative,
    /// or when <paramref name="detectionTick"/> is negative.
    /// </exception>
    public PerceivedObject(
        ulong objectId,
        PerceivedObjectKind objectKind,
        SensorType sensorType,
        int confidence,
        int distance,
        long detectionTick)
    {
        if (confidence < 0 || confidence > 1000)
        {
            throw new ArgumentOutOfRangeException(nameof(confidence), "The perception confidence must be between 0 and 1000.");
        }

        if (distance < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(distance), "The perception distance must be zero or greater.");
        }

        if (detectionTick < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(detectionTick), "The detection tick must be zero or greater.");
        }

        ObjectId = objectId;
        ObjectKind = objectKind;
        SensorType = sensorType;
        Confidence = confidence;
        Distance = distance;
        DetectionTick = detectionTick;
    }

    /// <summary>
    /// Gets the deterministic observed object identifier.
    /// </summary>
    public ulong ObjectId { get; }

    /// <summary>
    /// Gets the observed object category.
    /// </summary>
    public PerceivedObjectKind ObjectKind { get; }

    /// <summary>
    /// Gets the sensor that produced the observation.
    /// </summary>
    public SensorType SensorType { get; }

    /// <summary>
    /// Gets the deterministic confidence scaled to the inclusive range [0, 1000].
    /// </summary>
    public int Confidence { get; }

    /// <summary>
    /// Gets the chunk distance between observer and observed object.
    /// </summary>
    public int Distance { get; }

    /// <summary>
    /// Gets the simulation tick when the detection occurred.
    /// </summary>
    public long DetectionTick { get; }
}
